### ISSUE TITLE
script and base tag support.

### ISSUE THREAD

**Issue by DylanPiercey** [pawsong/hairdresser#1]
I am using react and in the past have relied on "react-helmet" to accomplish isomorphic head rendering.

This library looks like an awesome and more intuitive replacement, however it is missing two features that I need, the ability to add `<base>` and `<script>` tags to the head.

Would this be possible to add?

Thanks for your work on this!

**Comment by pawsong** [comment]
Thank you for your attention! It's not a big deal and gonna be added soon.

**Comment by pawsong** [comment]
Now new version released. I have add `override.tag` function, which can be used to add element with given tag name. Controller option `close` is also added. It indicates whether to append closing tag when `renderToString`. This is an example:

``` javascript
var hairdresser = Hairdresser.create();
var override = hairdresser.override()
  .title('Hello, world!')
  .tag('base', { id: 'base' }, { href: 'http://www.example.com/page.html' })
  .tag('script', { id: 'script' }, { src: '/script.js' }, { close: true });

var ret = hairdresser.renderToString();
assert.equal(ret,
  '<base id="base" href="http://www.example.com/page.html">' +
  '<script id="script" src="/script.js"></script>' +
  '<title>Hello, world!</title>'
);
```

To keep your code simple, you can declare custom method for specific tag like this: 

``` javascript
var hairdresser = Hairdresser.create();
hairdresser.Override.prototype.base = function (attrs, render, options) {
  return this.tag('base', attrs, render, options);
};
hairdresser.Override.prototype.script = function (attrs, render, options) {
  var opts = options || {};
  opts.close = true;
  return this.tag('script', attrs, render, opts);
};

var override = hairdresser.override()
  .title('Hello, world!')
  .base({ id: 'base' }, { href: 'http://www.example.com/page.html' })
  .script({ id: 'script' }, { src: '/script.js' });

var ret = hairdresser.renderToString();
assert.equal(ret,
  '<base id="base" href="http://www.example.com/page.html">' +
  '<script id="script" src="/script.js"></script>' +
  '<title>Hello, world!</title>'
);
```

Please let me know if there is another issue!

**Comment by DylanPiercey** [comment]
Thanks for the fix will try it out soon!

**Comment by DylanPiercey** [comment]
@pawsong Any chance #script and #base could be added to this lib. by default?
