### ISSUE TITLE
Footer support.

### ISSUE THREAD

**Issue by DylanPiercey** [pawsong/hairdresser#3]
Hey I am just thinking that it would be handy if there was a way to say which element that hairdresser ran from.

Specifically I am looking for something that can universally render a header and a footer (with scripts for an app).

Perhaps something like
```js
const headRenderer = hairdresser.create() // defaults to head.
const footRenderer = hairdresser.create('footer') // selects a footer element.
```

The server side rendering would stay more/less the same.
What are your thoughts on this?

**Comment by pawsong** [comment]
Thank you for your suggestion and sorry for the delayed reply.

The feature looks nice to me. The element to attach `hairdresser` output is required only on client-side, so how about this API?

``` javascript
const hairdresser = Hairdresser.create();

// Add stuff to hairdresser ...

// Append output to `<head>` as default
hairdresser.render();

// or pass the parent element for hairdresser
hairdresser.render(document.querySelector('body'));

// or pass a selector to find the parent element
hairdresser.render('body');
```

If it's ok, I will look into it on this weekend!

**Comment by DylanPiercey** [comment]
Makes sense to me. Thanks for your work in this lib :).

**Comment by pawsong** [comment]
v3.0 has been released with this feature! [This test code](https://github.com/pawsong/hairdresser/blob/03947c2f8460b4f5d47b41601c61f0c7788d3594/test/Hairdresser.test.ts#L485) might be an example for it.

By the way, can I ask you which framework you use? I've started to write bridges for major libraries like React, and I might be able to set the framework you use to high :)

**Comment by DylanPiercey** [comment]
Awesome - great work!

I currently use a mix of [Rill](https://github.com/rill-js/rill) and occasionally React. I am currently working on a framework built on Rill that does everything out of the box and this lib will come in handy! Definitely will give this another go once I get a chance in the next few days.

Thanks again.
