### ISSUE TITLE
Meta tag deleted after this.override.restore()

### ISSUE THREAD

**Issue by VictorienTardif** [pawsong/hairdresser#4]
Hello, 
I have some default meta tags sent by the server.
I want to update these tags on some pages. 
These tags are not created via hairdresser, they are already on the dom before hairdresser is initialized.
The thing is, if I update a tag using hairdresser and then use the restore() function, the original meta tag is deleted instead of being restored. 

I think it is because the tags are not created via hairdresser but is there a way to handle this case?

Thank you!

**Comment by pawsong** [comment]
Thank you for reporting this issue! I will make a fix this weekend :)

**Comment by VictorienTardif** [comment]
Ok great! Thank you for your work

**Comment by VictorienTardif** [comment]
Hi, have you found a solution? When do you think you'll push the fix?
Thanks

**Comment by pawsong** [comment]
I was busy while wrapping up some projects sorry :( Can make time for this issue this Friday!

**Comment by VictorienTardif** [comment]
Ok thanks :)

**Comment by pawsong** [comment]
Sorry for being late :( Check out v0.3.1!

**Comment by VictorienTardif** [comment]
It seems ok, thanks!
